apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090 # 'prometheus' to nazwa usługi w docker-compose.yml
    access: proxy
    isDefault: true
    editable: true